go:
  # Whenever the Go version is updated here,
  # .circle/config.yml should also be updated.
  version: 1.16
repository:
  path: github.com/project-athena/athena-core
build:
  flags: -a -tags 'static_build'
  binaries:
    - name: athena-processor
      path: ./cmd/processor
    - name: athena-monitor
      path: ./cmd/monitor
tarball:
  files:
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
