db:
  dsn: "athena:athena@tcp(db:3306)/athena?charset=utf8"

monitor:
  poll-every: 10s
  directories:
      - "/uploads"
  processor-map:
    - type: filename
      regex: ".*sosreport.*.txt$"
      processor: sosreports

processor:
  base-tmpdir: "/tmp/athena"
  subscribers:
    sosreports:
      sf-comment-enabled: true
      sf-comment-batch: 5m
      sf-comment-public: false
      sf-comment: |
        Athena

        Processor: {{ processor }} has run the following reports on file: {{ filename }}

        {% for report_name, _ in reports %}
         * {{ report_name }}: {{ pastebin_url }}
        {% endfor %}


        ----

      reports:
        hotsos:
          exit-codes: 0 2 127 126
          script: |
            #!/bin/bash
            echo ${{filepath}} ${{basedir}} && exit 0

filescom:
  key: "adc017510b7dec542da7494558d6567f42be0a8fa958497aef0b968738ab2035"
  endpoint: "https://app.files.com"

salesforce:
  endpoint: "https://canonical--obiwan.my.salesforce.com/"
  username: "jorge.niedbalski@canonical.com.obiwan"
  password: "avocado4life"
  security-token: "qi84gPBTXzee6sI7nlEnQXcWM"