db:
  dialect: mysql
  dsn: "athena:athena@tcp(db:3306)/athena?charset=utf8&parseTime=true"

monitor:
  poll-every: 10s
  files-delta: 10m
  directories:
      - "/uploads"
  processor-map:
    - type: filename
      regex: ".*sosreport.*.txt$"
      processor: sosreports

processor:
  batch-comments-every: 5m
  base-tmpdir: "/tmp/athena"
  subscribers:
    sosreports:
      sf-comment-enabled: true
      sf-comment-public: false
      sf-comment: |
        Athena

        Processor: {{ processor }} Subscriber: {{ subscriber }} has run the following reports:

        {% for report in reports %}
          * {{ report.Name }}: https://files.support.canonical.com/files/{{report.UploadLocation}}
        {% endfor %}

      reports:
        hotsos:
          exit-codes: 0 2 127 126
          script: |
            #!/bin/bash
            echo ${{filepath}} ${{basedir}} && exit 0
        foobar:
          exit-codes: 0
          script: |
            #!/bin/bash
            echo "foobar" && exit 0

filescom:
  key: "xxx"
  endpoint: "https://app.files.com"

salesforce:
  endpoint: "https://xxx--xxx.my.salesforce.com/"
  username: "xxx.xxx@xxx.com.xxx"
  password: "xxx"
  security-token: "xxx"