on: [push]
name: Publish snapstore edge
  ${GITHUB_SHA::8}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace snapcraft version/grade
        run: sed -i -e "s/\$VERSION/${GITHUB_SHA::8}/g" snap/snapcraft.yaml
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
