on: [push]
name: Publish snapstore edge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: actions/checkout@v2
      - name: Replace snapcraft version/grade
        run: sed -i -e "s/\$VERSION/${{ steps.vars.outputs.sha_short }}/g" snap/snapcraft.yaml
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
