on:
  push:
    tags:
      - '*'
name: Publish snapstore release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Replace snapcraft version/grade
        run: sed -i -e "s/\$VERSION/${{ steps.get_version.outputs.VERSION }}/g" snap/snapcraft.yaml
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable