on: [push, pull_request]
name: Build Snaps
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Replace snapcraft version/grade
        run: sed -i -e "s/\$VERSION/${{ steps.vars.outputs.sha_short }}/g" snap/snapcraft.yaml
      - name: Snapcraft Action
        uses: samuelmeuli/action-snapcraft@v1.1.3
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          use_lxd: true
      - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd'
